# enlisted
- type: rank
  id: UPP_Private
  name: Private
  prefix: Pvt.
  paygrade: E1

- type: rank
  id: UPP_Gefreiter
  name: Gefreiter
  prefix: Gefr.
  paygrade: E2

- type: rank
  id: UPP_SeniorGefreiter
  name: Senior Gefreiter
  prefix: SGefr.
  paygrade: E3

- type: rank
  id: UPP_Plutonowy
  name: Plutonowy
  prefix: Plut.
  paygrade: E3

- type: rank
  id: UPP_Sergeant
  name: Sergeant
  prefix: SSgt.
  paygrade: E5

- type: rank
  id: UPP_StaffSergeant
  name: Staff Sergeant
  prefix: SSgt.
  paygrade: E6

- type: rank
  id: UPP_Chotar
  name: Chotar
  prefix: Chot.
  paygrade: E7

- type: rank
  id: UPP_FirstSergeant
  name: First Sergeant
  prefix: 1stSgt.
  paygrade: E8

#  warrant Officers
- type: rank
  id: UPP_WarrantOfficer
  name: Warrant Officer
  prefix: WO.
  paygrade: W1

- type: rank
  id: UPP_SeniorWarrantOfficer
  name: Senior Warrant Officer
  prefix: Sen WO.
  paygrade: W2

# officers
- type: rank
  id: UPP_Leutenant
  name: Junior Leutenant
  prefix: JLt.
  paygrade: O1

- type: rank
  id: UPP_Leutenant
  name: Leutenant
  prefix: Lt.
  paygrade: O2

- type: rank
  id: UPP_Captain
  name: Captain
  prefix: Capt.
  paygrade: O3


#field officers
- type: rank
  id: UPP_Major
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: UPP_Podpolkovnik
  name: Lieutenant Colonel
  prefix: Lt Col.
  paygrade: O5

- type: rank
  id: UPP_Polkovnik
  name: Colonel
  prefix: Col.
  paygrade: O6

# Generals
- type: rank
  id: UPP_GeneralMajor
  name: General-Major
  prefix: GenMaj.
  paygrade: O7

- type: rank
  id: UPP_GeneralLieutenant
  name: General-Lieutenant
  prefix: GenLt.
  paygrade: O8

- type: rank
  id: UPP_GeneralColonel
  name: General-Colonel
  prefix: GenCol.
  paygrade: O9

- type: rank
  id: UPP_Marshal
  name: Marshal
  prefix: Marsh.
  paygrade: O10

- type: rank
  id: UPP_ChairmanMilitaryCouncil
  name: Chairman of Military Council
  prefix: CMC
  paygrade: O10

- type: rank
  id: UPP_Commissar
  name: Commissar
  prefix: Comrade