- type: job
  parent: AUThreatJobBase
  id: AU14JobThreatLeader
  name: au-job-name-threat-leader
  setPreference: true
  playTimeTracker: AUJobThreatLeader
  hidden: false
  supervisors: nobody
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: AU14JobThreatMember
    time: 7200 # 2 hours
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen

- type: playTimeTracker
  id: AUJobThreatLeader


